### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.formwidget.multifile#10]
Can we have a new release?  Or add `plone` to the PyPI owners?
@jone @davisagli @sneridagh

**Comment by gforcada** [comment]
maybe after merging #9 ?

**Comment by gforcada** [comment]
#9 was merged @jone @davisagli @sneridagh would you mind releasing or giving pypi rights to ``plone``?

**Comment by jone** [comment]
I've added `plone` as pypi owner.

**Comment by gforcada** [comment]
@jone thanks!

@mauritsvanrees @tomgross I made a 2.0 release given the amount of incompatible changes listed.

**Comment by mauritsvanrees** [comment]
Thanks all!
